import type { TourStep } from "./types";

export const tourSteps: TourStep[] = [
  {
    id: "intro",
    title: "Steel Connect — infraestrutura B2B do mercado de aço",
    body: "Em 60 segundos você vai ver: demanda anônima, micro-leilão reverso ao vivo, escrow + trava fiscal, logística com prova criptográfica e split automático. (Há também modo manual coleta de ofertas — RFQ — ao criar uma demanda, para demos alternativas.)",
    path: "/",
    duration: 4500,
  },
  {
    id: "buyer",
    title: "Painel do Comprador",
    body: "Construtora Vértice — KYB ATIVO, CNPJ validado. Vamos publicar uma demanda no marketplace anônimo.",
    path: "/buyer",
    duration: 3500,
  },
  {
    id: "open-form",
    title: "Criar nova demanda",
    body: "Formulário simples: produto, norma, volume, entrega, prazo e preço-alvo confidencial.",
    path: "/buyer",
    click: '[data-tour="new-demand"]',
    duration: 3000,
  },
  {
    id: "fill-form",
    title: "Preço-alvo é confidencial",
    body: "O sistema esconde o preço-alvo do mercado. Fornecedores nunca veem seu orçamento máximo.",
    path: "/buyer/new",
    duration: 4500,
  },
  {
    id: "publish",
    title: "Publicar no marketplace anônimo",
    body: "Demanda anonimizada. Identidade do comprador só é revelada após o leilão.",
    path: "/buyer/new",
    click: '[data-tour="submit-demand"]',
    capture: "demandId",
    duration: 2500,
  },
  {
    id: "matches",
    title: "Mercado dá match em segundos",
    body: "Fornecedores e transportadoras manifestam interesse. Sem negociação direta nesta fase.",
    duration: 3500,
  },
  {
    id: "select",
    title: "Comprador seleciona quem entra",
    body: "Escolha por score, selos e histórico. Mínimo: 2 fornecedores e 2 transportadoras.",
    duration: 4500,
  },
  {
    id: "start-auction",
    title: "Iniciar micro-leilão reverso",
    body: "Sala privada, lances apenas decrescentes, dois leilões em paralelo: produto + frete.",
    click: '[data-tour="start-auction"]',
    duration: 2500,
  },
  {
    id: "auction-live",
    title: "🔥 Leilão ao vivo — soft close ativo",
    body: "Fornecedores derrubam preço em tempo real. Lance nos últimos 8s aciona overtime automático. Server-time UTC é a única autoridade.",
    duration: 11000,
  },
  {
    id: "auction-end",
    title: "Vencedores definidos pelo mercado",
    body: "Contrato gerado automaticamente unindo o vencedor do produto com o vencedor do frete.",
    duration: 3500,
  },
  {
    id: "goto-contract",
    title: "Contrato + FSM",
    body: "Máquina de estados normativa. Cada transição é evento auditável.",
    click: '[data-tour="goto-contract"]',
    capture: "contractId",
    duration: 3000,
  },
  {
    id: "accept",
    title: "Comprador aceita os termos",
    body: "Em produção: assinatura digital A1 vinculada ao CNPJ.",
    click: '[data-tour="accept-contract"]',
    duration: 2500,
  },
  {
    id: "goto-escrow",
    title: "Escrow + Trava Fiscal",
    body: "Banco trava 100% do valor. Sistema lê <vNF> do XML e compara com o escrow.",
    click: '[data-tour="goto-escrow"]',
    duration: 3000,
  },
  {
    id: "upload-nf",
    title: "Trava Fiscal em ação",
    body: "Tolerância R$ 1,00. Diferença de R$ 0,30 → aprovação automática + token de carga emitido.",
    click: '[data-tour="upload-nf"]',
    duration: 4500,
  },
  {
    id: "goto-logistics",
    title: "Logística offline-first",
    body: "Realidade física comprovada prevalece sobre intenções digitais (tolerância 6h).",
    click: '[data-tour="goto-logistics-from-escrow"]',
    duration: 3000,
  },
  {
    id: "deliver",
    title: "Caminhão entrega + assinatura criptográfica",
    body: "App do motorista funciona offline. GPS + assinatura digital + hash. Tudo verificável.",
    click: '[data-tour="confirm-delivery"]',
    duration: 3500,
  },
  {
    id: "window",
    title: "Janela de 72h — silêncio = aceite",
    body: "Comprador pode contestar. No demo, 30s simulam 72h. Vamos pular.",
    click: '[data-tour="skip-window"]',
    duration: 3000,
  },
  {
    id: "concluded",
    title: "Split automático em uma transação",
    body: "Fornecedor + Transportadora + Steel Connect recebem. Take rate efetivo de ~1,1% sobre GMV.",
    duration: 5000,
  },
  {
    id: "admin",
    title: "Visão de plataforma · Business Heartbeat",
    body: "GMV, conversão, alertas, audit log append-only. Vamos conversar?",
    path: "/admin",
    duration: 5000,
  },
];
